### ISSUE TITLE
[Todo] Add Enhancement and Temporal metals

### ISSUE THREAD

**Issue by Halyo-Alex** [Frontrider/Allomancy#2]
Enhancement:

- [ ] Aluminum (removes all metal reserves from the player who burns it)
- [ ] Duralumin (burns away all active metal reserves immediately for a massive power boost related to those metals)
- [ ] Chromium (removes all metal reserves from the players touched by the player burning it)
- [ ] Nicrosil (Burns away all active metal reserves immediately, from the players touched by the player burning it, for a massive power boost related to those metals)

Temporal:

- [ ] Gold (renders a copy of the player clientside with randomly generated armor/held item)
- [ ] Electrum (renders several copies of the player clientside with random pathfinding/actions)
- [ ] Cadmium (generates a Lingering Potion of Slowness around the player when they start to burn it)
- [ ] Bendalloy (generates a Lingering Potion of Swiftness around the player when they start to burn it)
